#!/usr/bin/env bash
#
# scripts/stats.sh — keep the README's numbers honest, automatically.
#
# The "Project stats" block in README.md is generated, not hand-typed.
# This script recomputes every figure from the repository itself and
# rewrites the region between
#
#     <!-- STATS:START -->   …generated…   <!-- STATS:END -->
#
# in README.md. It is wired to run:
#   • on every commit  — via .githooks/pre-commit (re-stages README), and
#   • on every push/PR — via .github/workflows/stats.yml
# so the numbers can never drift from reality again.
#
# Usage:
#   scripts/stats.sh            rewrite README.md in place
#   scripts/stats.sh --check    exit 1 if README.md is out of date
#                               (don't modify it) — for CI / PRs
#
# Counts ONLY the from-scratch userland: the bundled Linux kernel and
# the Buildroot tree (buildroot/) are deliberately excluded.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

README="README.md"
MARK_START="<!-- STATS:START -->"
MARK_END="<!-- STATS:END -->"

# --- gather the list of our Rust files (tracked, excluding buildroot) ---
# Fall back to `find` when not in a git work tree (fresh CI checkout edge).
if git rev-parse --git-dir >/dev/null 2>&1; then
  mapfile -t RS_FILES < <(git ls-files '*.rs' | grep -v '^buildroot/' || true)
  TRACKED=$(git ls-files | grep -vc '^buildroot/' || echo 0)
  COMMITS=$(git rev-list --count HEAD 2>/dev/null || echo 0)
  FIRST_DAY=$(git log --reverse --format=%ad --date=short 2>/dev/null | head -1 || echo "?")
  LAST_DAY=$(git log -1 --format=%ad --date=short 2>/dev/null || echo "?")
else
  mapfile -t RS_FILES < <(find . -name '*.rs' -not -path './buildroot/*' -not -path './target/*' | sed 's|^\./||')
  TRACKED=$(find . -type f -not -path './buildroot/*' -not -path './.git/*' -not -path './target/*' | wc -l)
  COMMITS=0; FIRST_DAY="?"; LAST_DAY="?"
fi

FILES=${#RS_FILES[@]}
LOC=$( (printf '%s\n' "${RS_FILES[@]}" | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}') || echo 0)
TESTS=$( (grep -hoE '#\[(test|tokio::test)\]' "${RS_FILES[@]}" 2>/dev/null | wc -l) || echo 0)

# Workspace crate count = members listed in the root Cargo.toml.
CRATES=$(awk '/^\s*members\s*=\s*\[/{f=1;next} /\]/{f=0} f{print}' Cargo.toml \
          | grep -c '"' || echo 0)

# --- per-crate line counts, biggest first -----------------------------
declare -A CRATE_LOC
for d in drdr-*; do
  [ -d "$d/src" ] || continue
  n=$(find "$d/src" -name '*.rs' -print0 | xargs -0 wc -l 2>/dev/null \
        | tail -1 | awk '{print $1}')
  [ -n "${n:-}" ] && CRATE_LOC["$d"]=$n
done

PURPOSE_drdr_ui="GUI framework + WM + shell"
PURPOSE_drdr_net="binary proto + reactor"
PURPOSE_drdr_desk="window manager + apps"
PURPOSE_drdr_font="8x16 glyphs"
PURPOSE_drdr_shell="shell"
PURPOSE_drdr_files="file browser"
PURPOSE_drdr_init="PID 1 / supervisor"
PURPOSE_drdr_fb="framebuffer (all bpp)"
PURPOSE_drdr_store="persistent storage"
PURPOSE_drdr_demo="widget showcase"
PURPOSE_drdr_tty="raw-mode helper"
PURPOSE_drdr_edit="modal editor"

crate_rows() {
  for d in $(for k in "${!CRATE_LOC[@]}"; do echo "${CRATE_LOC[$k]} $k"; done \
              | sort -rn | awk '{print $2}'); do
    key="PURPOSE_${d//-/_}"
    printf '| %-10s | %5s | %s |\n' "$d" "${CRATE_LOC[$d]}" "${!key:-—}"
  done
}

# --- assemble the generated block -------------------------------------
BLOCK="$(cat <<EOF
$MARK_START
<!-- Generated by scripts/stats.sh — do not edit by hand.
     Refreshed automatically on every commit (.githooks/pre-commit)
     and every push (.github/workflows/stats.yml). -->

| Metric | Value |
|---|---|
| Rust source | **$LOC lines** across **$FILES files** |
| Workspace crates | **$CRATES** (every \`drdr-*\`) |
| Tests | **$TESTS** (\`cargo test\`, all green) |
| Git commits | **$COMMITS** |
| Tracked files (excl. \`buildroot/\`) | **$TRACKED** |
| Development window | $FIRST_DAY → $LAST_DAY |

Lines of Rust per crate (largest first):

| Crate | Lines | Purpose |
|---|--:|---|
$(crate_rows)
$MARK_END
EOF
)"

# --- splice it into README.md -----------------------------------------
if ! grep -qF "$MARK_START" "$README" || ! grep -qF "$MARK_END" "$README"; then
  echo "stats.sh: markers $MARK_START / $MARK_END not found in $README" >&2
  exit 2
fi

NEW="$(awk -v start="$MARK_START" -v end="$MARK_END" -v block="$BLOCK" '
  $0 ~ start {print block; skip=1; next}
  $0 ~ end   {skip=0; next}
  !skip      {print}
' "$README")"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q <(printf '%s\n' "$NEW") "$README" >/dev/null 2>&1; then
    echo "stats.sh: README.md is out of date — run scripts/stats.sh" >&2
    exit 1
  fi
  echo "stats.sh: README.md stats are up to date."
  exit 0
fi

printf '%s\n' "$NEW" > "$README"
echo "stats.sh: README.md stats refreshed ($LOC LOC, $FILES files, $TESTS tests, $COMMITS commits)."
